repo:
- any: ['*','!Dockerfile','!.dockerignore']

source:
- any: ['src/*','!src/plot/*']

plot:
- 'src/plot/*'

header:
- 'header/*'

documentation:
- 'Documentation/*'

github:
- '.github/*'

docker:
- any: ['Dockerfile','.dockerignore']
