name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Greetings, friend! Welcome on this probabilistic calculus project! I hope you'll find it interesting and help me to achieve it!"
        pr-message: "Hail, friend! Thank you for submitting your code for review! I hope we will still work together by the future!"
